api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: vdelaluz@enesmorelia.unam.mx
      storage: acme.json
      tlsChallenge: {}
